pa11y

diff --git a/.github/workflows/pushto_test_pa11y.yml b/.github/workflows/pushto_test_pa11y.yml
--- a/.github/workflows/pushto_test_pa11y.yml
+++ b/.github/workflows/pushto_test_pa11y.yml
@@ -27,7 +27,6 @@ jobs:
 
     steps:
 
-
       - name: download pa11y-ci
         run: |
           sudo npm install -g npm@latest
@@ -37,7 +36,8 @@ jobs:
       - name: run pa11y
         run: |
           set -x
-          (sudo pa11y-ci --json --config ./setup/pa11y_config.json --sitemap https://staging.londonparkour.com/sitemap_index.xml &>> /tmp/pa11y-results.json) || true
+          echo "{ "defaults": { "ignore": [ "WCAG2AA.Principle1.Guideline1_4.1_4_3.G145.Fail", "WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail" ] } }" > pa11y_config.json
+          ( pa11y-ci --json --config pa11y_config.json --sitemap https://staging.londonparkour.com/sitemap_index.xml &>> /tmp/pa11y-results.json) || true
 
       # # DEBUG with NGROK.
       - name: Start SSH session
